# Generated by Django 2.2.2 on 2019-07-02 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
