# Generated by Django 2.2.2 on 2019-07-02 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='problem_url',
            new_name='url',
        ),
    ]
