# Generated by Django 2.2.2 on 2019-07-02 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_auto_20190702_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='from_year',
            field=models.IntegerField(default=2002),
        ),
    ]
