# Generated by Django 3.0.5 on 2020-04-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_auto_20190706_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
