# Generated by Django 2.2.2 on 2019-07-02 03:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_auto_20190630_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='url',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
