# Generated by Django 2.2.2 on 2019-07-02 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_auto_20190702_0844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='id',
            new_name='abbreviation',
        ),
    ]
