# Generated by Django 2.2.2 on 2019-07-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_auto_20190702_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='url',
            field=models.URLField(default='https://oj.uz/'),
        ),
    ]
