# Generated by Django 2.2.2 on 2019-07-02 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0005_auto_20190702_0857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='url',
            new_name='problem_url',
        ),
    ]
